function negrad_Lw = neggrad_loglikelihood_softmax(all_w,x,y,nstates, weights,...
					      ptr_func,ptr_gradfunc, lambda_w)

negrad_Lw = - grad_loglikelihood_softmax(all_w,x,y,nstates, weights,...
					 ptr_func, ptr_gradfunc, lambda_w);
